
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.VBox vbox3;

	private global::Gtk.Label procc;

	private global::Gtk.Entry entry2;

	private global::Gtk.Label total;

	private global::Gtk.Table table4;

	private global::Gtk.Button dividebttn;

	private global::Gtk.Button eightbttn;

	private global::Gtk.Button equalbttn;

	private global::Gtk.Button fivebttn;

	private global::Gtk.Button fourbttn;

	private global::Gtk.Button minusbttn;

	private global::Gtk.Button ninebttn;

	private global::Gtk.Button onebttn;

	private global::Gtk.Button plusbttn;

	private global::Gtk.Button sevenbttn;

	private global::Gtk.Button sixbttn;

	private global::Gtk.Button threebttn;

	private global::Gtk.Button timebttn;

	private global::Gtk.Button twobttn;

	private global::Gtk.Button zerobttn;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox3 = new global::Gtk.VBox();
		this.vbox3.Name = "vbox3";
		this.vbox3.Spacing = 6;
		// Container child vbox3.Gtk.Box+BoxChild
		this.procc = new global::Gtk.Label();
		this.procc.Name = "procc";
		this.vbox3.Add(this.procc);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.procc]));
		w1.Position = 0;
		w1.Expand = false;
		w1.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.entry2 = new global::Gtk.Entry();
		this.entry2.CanFocus = true;
		this.entry2.Name = "entry2";
		this.entry2.Text = global::Mono.Unix.Catalog.GetString("0");
		this.entry2.IsEditable = true;
		this.entry2.InvisibleChar = '•';
		this.entry2.Xalign = 1F;
		this.vbox3.Add(this.entry2);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.entry2]));
		w2.Position = 1;
		w2.Expand = false;
		w2.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.total = new global::Gtk.Label();
		this.total.Name = "total";
		this.vbox3.Add(this.total);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.total]));
		w3.Position = 2;
		w3.Expand = false;
		w3.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.table4 = new global::Gtk.Table(((uint)(4)), ((uint)(5)), false);
		this.table4.Name = "table4";
		this.table4.RowSpacing = ((uint)(6));
		this.table4.ColumnSpacing = ((uint)(6));
		this.table4.BorderWidth = ((uint)(3));
		// Container child table4.Gtk.Table+TableChild
		this.dividebttn = new global::Gtk.Button();
		this.dividebttn.CanFocus = true;
		this.dividebttn.Name = "dividebttn";
		this.dividebttn.UseUnderline = true;
		this.dividebttn.Label = global::Mono.Unix.Catalog.GetString("/");
		this.table4.Add(this.dividebttn);
		global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.table4[this.dividebttn]));
		w4.TopAttach = ((uint)(2));
		w4.BottomAttach = ((uint)(3));
		w4.LeftAttach = ((uint)(4));
		w4.RightAttach = ((uint)(5));
		w4.XOptions = ((global::Gtk.AttachOptions)(4));
		w4.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table4.Gtk.Table+TableChild
		this.eightbttn = new global::Gtk.Button();
		this.eightbttn.CanFocus = true;
		this.eightbttn.Name = "eightbttn";
		this.eightbttn.UseUnderline = true;
		this.eightbttn.Label = global::Mono.Unix.Catalog.GetString("8");
		this.table4.Add(this.eightbttn);
		global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.table4[this.eightbttn]));
		w5.LeftAttach = ((uint)(2));
		w5.RightAttach = ((uint)(3));
		w5.XOptions = ((global::Gtk.AttachOptions)(4));
		w5.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table4.Gtk.Table+TableChild
		this.equalbttn = new global::Gtk.Button();
		this.equalbttn.CanFocus = true;
		this.equalbttn.Name = "equalbttn";
		this.equalbttn.UseUnderline = true;
		this.equalbttn.Label = global::Mono.Unix.Catalog.GetString("=");
		this.table4.Add(this.equalbttn);
		global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.table4[this.equalbttn]));
		w6.TopAttach = ((uint)(3));
		w6.BottomAttach = ((uint)(4));
		w6.LeftAttach = ((uint)(3));
		w6.RightAttach = ((uint)(4));
		w6.XOptions = ((global::Gtk.AttachOptions)(4));
		w6.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table4.Gtk.Table+TableChild
		this.fivebttn = new global::Gtk.Button();
		this.fivebttn.CanFocus = true;
		this.fivebttn.Name = "fivebttn";
		this.fivebttn.UseUnderline = true;
		this.fivebttn.Label = global::Mono.Unix.Catalog.GetString("5");
		this.table4.Add(this.fivebttn);
		global::Gtk.Table.TableChild w7 = ((global::Gtk.Table.TableChild)(this.table4[this.fivebttn]));
		w7.TopAttach = ((uint)(1));
		w7.BottomAttach = ((uint)(2));
		w7.LeftAttach = ((uint)(2));
		w7.RightAttach = ((uint)(3));
		w7.XOptions = ((global::Gtk.AttachOptions)(4));
		w7.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table4.Gtk.Table+TableChild
		this.fourbttn = new global::Gtk.Button();
		this.fourbttn.CanFocus = true;
		this.fourbttn.Name = "fourbttn";
		this.fourbttn.UseUnderline = true;
		this.fourbttn.Label = global::Mono.Unix.Catalog.GetString("4");
		this.table4.Add(this.fourbttn);
		global::Gtk.Table.TableChild w8 = ((global::Gtk.Table.TableChild)(this.table4[this.fourbttn]));
		w8.TopAttach = ((uint)(1));
		w8.BottomAttach = ((uint)(2));
		w8.LeftAttach = ((uint)(1));
		w8.RightAttach = ((uint)(2));
		w8.XOptions = ((global::Gtk.AttachOptions)(4));
		w8.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table4.Gtk.Table+TableChild
		this.minusbttn = new global::Gtk.Button();
		this.minusbttn.CanFocus = true;
		this.minusbttn.Name = "minusbttn";
		this.minusbttn.UseUnderline = true;
		this.minusbttn.Label = global::Mono.Unix.Catalog.GetString("-");
		this.table4.Add(this.minusbttn);
		global::Gtk.Table.TableChild w9 = ((global::Gtk.Table.TableChild)(this.table4[this.minusbttn]));
		w9.TopAttach = ((uint)(1));
		w9.BottomAttach = ((uint)(2));
		w9.LeftAttach = ((uint)(4));
		w9.RightAttach = ((uint)(5));
		w9.XOptions = ((global::Gtk.AttachOptions)(4));
		w9.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table4.Gtk.Table+TableChild
		this.ninebttn = new global::Gtk.Button();
		this.ninebttn.CanFocus = true;
		this.ninebttn.Name = "ninebttn";
		this.ninebttn.UseUnderline = true;
		this.ninebttn.Label = global::Mono.Unix.Catalog.GetString("9");
		this.table4.Add(this.ninebttn);
		global::Gtk.Table.TableChild w10 = ((global::Gtk.Table.TableChild)(this.table4[this.ninebttn]));
		w10.LeftAttach = ((uint)(3));
		w10.RightAttach = ((uint)(4));
		w10.XOptions = ((global::Gtk.AttachOptions)(4));
		w10.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table4.Gtk.Table+TableChild
		this.onebttn = new global::Gtk.Button();
		this.onebttn.CanFocus = true;
		this.onebttn.Name = "onebttn";
		this.onebttn.UseUnderline = true;
		this.onebttn.Label = global::Mono.Unix.Catalog.GetString("1");
		this.table4.Add(this.onebttn);
		global::Gtk.Table.TableChild w11 = ((global::Gtk.Table.TableChild)(this.table4[this.onebttn]));
		w11.TopAttach = ((uint)(2));
		w11.BottomAttach = ((uint)(3));
		w11.LeftAttach = ((uint)(1));
		w11.RightAttach = ((uint)(2));
		w11.XOptions = ((global::Gtk.AttachOptions)(4));
		w11.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table4.Gtk.Table+TableChild
		this.plusbttn = new global::Gtk.Button();
		this.plusbttn.CanFocus = true;
		this.plusbttn.Name = "plusbttn";
		this.plusbttn.UseUnderline = true;
		this.plusbttn.Label = global::Mono.Unix.Catalog.GetString("+");
		this.table4.Add(this.plusbttn);
		global::Gtk.Table.TableChild w12 = ((global::Gtk.Table.TableChild)(this.table4[this.plusbttn]));
		w12.LeftAttach = ((uint)(4));
		w12.RightAttach = ((uint)(5));
		w12.XOptions = ((global::Gtk.AttachOptions)(4));
		w12.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table4.Gtk.Table+TableChild
		this.sevenbttn = new global::Gtk.Button();
		this.sevenbttn.CanFocus = true;
		this.sevenbttn.Name = "sevenbttn";
		this.sevenbttn.UseUnderline = true;
		this.sevenbttn.Label = global::Mono.Unix.Catalog.GetString("7");
		this.table4.Add(this.sevenbttn);
		global::Gtk.Table.TableChild w13 = ((global::Gtk.Table.TableChild)(this.table4[this.sevenbttn]));
		w13.LeftAttach = ((uint)(1));
		w13.RightAttach = ((uint)(2));
		w13.XOptions = ((global::Gtk.AttachOptions)(4));
		w13.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table4.Gtk.Table+TableChild
		this.sixbttn = new global::Gtk.Button();
		this.sixbttn.CanFocus = true;
		this.sixbttn.Name = "sixbttn";
		this.sixbttn.UseUnderline = true;
		this.sixbttn.Label = global::Mono.Unix.Catalog.GetString("6");
		this.table4.Add(this.sixbttn);
		global::Gtk.Table.TableChild w14 = ((global::Gtk.Table.TableChild)(this.table4[this.sixbttn]));
		w14.TopAttach = ((uint)(1));
		w14.BottomAttach = ((uint)(2));
		w14.LeftAttach = ((uint)(3));
		w14.RightAttach = ((uint)(4));
		w14.XOptions = ((global::Gtk.AttachOptions)(4));
		w14.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table4.Gtk.Table+TableChild
		this.threebttn = new global::Gtk.Button();
		this.threebttn.CanFocus = true;
		this.threebttn.Name = "threebttn";
		this.threebttn.UseUnderline = true;
		this.threebttn.Label = global::Mono.Unix.Catalog.GetString("3");
		this.table4.Add(this.threebttn);
		global::Gtk.Table.TableChild w15 = ((global::Gtk.Table.TableChild)(this.table4[this.threebttn]));
		w15.TopAttach = ((uint)(2));
		w15.BottomAttach = ((uint)(3));
		w15.LeftAttach = ((uint)(3));
		w15.RightAttach = ((uint)(4));
		w15.XOptions = ((global::Gtk.AttachOptions)(4));
		w15.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table4.Gtk.Table+TableChild
		this.timebttn = new global::Gtk.Button();
		this.timebttn.CanFocus = true;
		this.timebttn.Name = "timebttn";
		this.timebttn.UseUnderline = true;
		this.timebttn.Label = global::Mono.Unix.Catalog.GetString("*");
		this.table4.Add(this.timebttn);
		global::Gtk.Table.TableChild w16 = ((global::Gtk.Table.TableChild)(this.table4[this.timebttn]));
		w16.TopAttach = ((uint)(3));
		w16.BottomAttach = ((uint)(4));
		w16.LeftAttach = ((uint)(4));
		w16.RightAttach = ((uint)(5));
		w16.XOptions = ((global::Gtk.AttachOptions)(4));
		w16.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table4.Gtk.Table+TableChild
		this.twobttn = new global::Gtk.Button();
		this.twobttn.CanFocus = true;
		this.twobttn.Name = "twobttn";
		this.twobttn.Label = global::Mono.Unix.Catalog.GetString("2");
		this.table4.Add(this.twobttn);
		global::Gtk.Table.TableChild w17 = ((global::Gtk.Table.TableChild)(this.table4[this.twobttn]));
		w17.TopAttach = ((uint)(2));
		w17.BottomAttach = ((uint)(3));
		w17.LeftAttach = ((uint)(2));
		w17.RightAttach = ((uint)(3));
		w17.XOptions = ((global::Gtk.AttachOptions)(4));
		w17.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table4.Gtk.Table+TableChild
		this.zerobttn = new global::Gtk.Button();
		this.zerobttn.CanFocus = true;
		this.zerobttn.Name = "zerobttn";
		this.zerobttn.UseUnderline = true;
		this.zerobttn.Label = global::Mono.Unix.Catalog.GetString("0");
		this.table4.Add(this.zerobttn);
		global::Gtk.Table.TableChild w18 = ((global::Gtk.Table.TableChild)(this.table4[this.zerobttn]));
		w18.TopAttach = ((uint)(3));
		w18.BottomAttach = ((uint)(4));
		w18.LeftAttach = ((uint)(2));
		w18.RightAttach = ((uint)(3));
		w18.XOptions = ((global::Gtk.AttachOptions)(4));
		w18.YOptions = ((global::Gtk.AttachOptions)(4));
		this.vbox3.Add(this.table4);
		global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.table4]));
		w19.Position = 3;
		w19.Expand = false;
		this.Add(this.vbox3);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 198;
		this.DefaultHeight = 240;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.zerobttn.Clicked += new global::System.EventHandler(this.click);
		this.twobttn.Clicked += new global::System.EventHandler(this.click);
		this.timebttn.Clicked += new global::System.EventHandler(this.operation);
		this.threebttn.Clicked += new global::System.EventHandler(this.click);
		this.sixbttn.Clicked += new global::System.EventHandler(this.click);
		this.sevenbttn.Clicked += new global::System.EventHandler(this.click);
		this.plusbttn.Clicked += new global::System.EventHandler(this.operation);
		this.onebttn.Clicked += new global::System.EventHandler(this.click);
		this.ninebttn.Clicked += new global::System.EventHandler(this.click);
		this.minusbttn.Clicked += new global::System.EventHandler(this.operation);
		this.fourbttn.Clicked += new global::System.EventHandler(this.click);
		this.fivebttn.Clicked += new global::System.EventHandler(this.click);
		this.equalbttn.Clicked += new global::System.EventHandler(this.equal);
		this.eightbttn.Clicked += new global::System.EventHandler(this.click);
		this.dividebttn.Clicked += new global::System.EventHandler(this.operation);
	}
}
